version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: insur132
    ports:
      - 3306:3306
    volumes:
      - '$PWD/mysql-data/lib:/var/lib/mysql'
      - '$PWD/mysql-data/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysql.cnf'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data/:/data/

