version: '2'
services:
  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data/:/data/
  phpredisadmin:
    depends_on:
      - redis
    image: erikdubbelboer/phpredisadmin
    container_name: phpredisadmin
    restart: always
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=pass
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    ports:
      - "8082:80"
